from django.conf import settings
from django.db import models


# Create your models here.
class Portfolio(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    name = models.CharField(max_length=128)
    date_created = models.DateTimeField(auto_created=True)
    total_loan_balance = models.IntegerField()
    total_loan_count = models.IntegerField()
    average_loan_balance = models.DecimalField(decimal_places=2, max_digits=20)
    weighted_average_coupon = models.DecimalField(decimal_places=5, max_digits=20)
    weighted_average_life_to_maturity = models.DecimalField(decimal_places=5, max_digits=20)


class Loan(models.Model):
    portfolio = models.ForeignKey(Portfolio)
    as_of_date = models.DateField()
    property_type_code = models.CharField(max_length=3)
    occupancy_code = models.CharField(max_length=1)
    product_type = models.CharField(max_length=10)
    purpose = models.CharField(max_length=1)
    mortgage_type = models.CharField(max_length=5)
    lien_position = models.IntegerField()
    original_rate = models.DecimalField(decimal_places=4, max_digits=20)
    original_appraisal_amount = models.IntegerField()
    original_date = models.DateField()
    first_payment_date = models.DateField()
    original_amount = models.IntegerField()
    original_term = models.IntegerField()
    pmi_insurance = models.CharField(max_length=128)
    city = models.CharField(max_length=256)
    state = models.CharField(max_length=2)
    zipcode = models.CharField(max_length=5)
    fico = models.IntegerField()
    gross_margin = models.DecimalField(decimal_places=5, max_digits=20)
    lcap = models.DecimalField(decimal_places=5, max_digits=20)
    lfloor = models.DecimalField(decimal_places=5, max_digits=20)
    icap = models.DecimalField(decimal_places=3, max_digits=20)
    pcap = models.DecimalField(decimal_places=3, max_digits=20)
    interest_reset_interval = models.IntegerField()
    reset_index = models.CharField(max_length=6)
    first_index_rate_adjustment_date = models.DateField()
    first_recast_or_next_recast = models.DecimalField(decimal_places=3, max_digits=20)
    recast_frequency = models.IntegerField()
    recast_cap = models.IntegerField()
    negam_initial_minimum_payment_period = models.IntegerField()
    negam_payment_reset_frequency = models.IntegerField()

    # TODO Snapshot fields to be in LoanSnapShot class when functionality is added.
    # loan = models.ForeignKey(Loan)
    remaining_term = models.IntegerField()
    amortized_term = models.IntegerField()
    IO_term = models.IntegerField()
    status = models.CharField(max_length=7)
    deferred_balance = models.DecimalField(decimal_places=2, max_digits=20)
    modification_date = models.DateField()
    foreclosure_referral_date = models.DateField()
    current_property_value = models.IntegerField()
    current_value_date = models.DateField()
    current_principal_balance = models.DecimalField(decimal_places=2, max_digits=20)
    current_interest_rate = models.DecimalField(decimal_places=5, max_digits=20)
    last_payment_received = models.DateField()
    current_FICO_score = models.IntegerField()
    BK_flag = models.CharField(max_length=1)
    MSR = models.CharField(max_length=1)
    senior_lien_balance = models.DecimalField(decimal_places=3, max_digits=20)
    senior_lien_balance_date = models.DateField()
    second_lien_piggyback_flag = models.CharField(max_length=1)
    junior_lien_balance = models.IntegerField()
    SF = models.IntegerField()


# class LoanAdjustedAssumptions(models.Model):
#     loan = models.ForeignKey(Loan)  # TODO Change to loan snapshot when functionality is added.
#     adjusted_cdr = models.DecimalField()
#     adjusted_cpr = models.DecimalField()
#     adjusted_recovery = models.DecimalField()
#     adjusted_lag = models.DecimalField()
